#!/usr/bin/env bash

base_name="pico-8"
version="0.2.7"
arch_name="amd64"
ARCH=x86_64

# "amd64" "i386" "raspi"

# pico-8_0.2.7_amd64.zip
# pico-8_0.2.7_i386.zip
# pico-8_0.2.7_raspi.zip

# target: pico-8_0.2.7_amd64.appimage

appname="${base_name}_${version}_${arch_name}"
app_dirname=$(echo "$base_name" | sed -E 's/[^[:alnum:]]+//g; s/.*/\L&/; s/\b\w/\u&/g') # remove special chars and change to Title case
app_dirname="${app_dirname}.AppDir" # Pico8

echo "processing $appname"

set -e # abort on error

unzip $appname.zip
mkdir -p $app_dirname/usr/bin
mkdir -p $app_dirname/usr/share/metainfo
cp pico-8/pico8 $app_dirname/usr/bin/
cp pico-8/pico8.dat $app_dirname/usr/bin/
ln -s usr/bin/pico8 $app_dirname/AppRun
convert pico-8/lexaloffle-pico8.png -resize 256x256\! $app_dirname/lexaloffle-pico8.png
chmod +x $app_dirname/usr/bin/pico8
chmod +x $app_dirname/AppRun

cat > $app_dirname/Pico-8.desktop <<EOL
[Desktop Entry]
Name=Pico-8
Exec=pico8
Icon=lexaloffle-pico8
Type=Application
Categories=Game;
Comment=Fantasy Console for Making, Sharing and Playing Tiny Games and Other Computer Programs.
EOL

cat > $app_dirname/usr/share/metainfo/com.lexaloffle.pico8.appdata.xml <<EOL
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
    <id>com.lexaloffle.pico8.desktop</id>
    <name>PICO-8</name>
    <summary>Fantasy console for making, sharing and playing tiny games</summary>
    <description>
        <p>PICO-8 is a fantasy console for creating, sharing and playing small games and programs. It features a custom code editor, sprite editor, map editor, sound editor and more.</p>
    </description>
    <developer_name>Lexaloffle Games</developer_name>
    <launchable type="desktop-id">Pico-8.desktop</launchable>
    <icon type="stock">lexaloffle-pico8</icon>
    <url type="homepage">https://www.lexaloffle.com/pico-8.php</url>
    <url type="help">https://pico-8.fandom.com/wiki/Pico-8_Wikia</url>
    <provides>
        <binary>pico8</binary>
    </provides>
    <categories>
        <category>Game</category>
        <category>Development</category>
    </categories>
    <metadata_license>FSFAP</metadata_license>
    <content_rating type="oars-1.1" />
    <agreement type="eula" version_id="1.0">
        <agreement_section id="pico-8">
            <name>SOFTWARE LICENSE AGREEMENT FOR PICO-8</name>
            <description>
                <p>This license agreement is between you, the end user, and Lexaloffle Games LLP ("LEXALOFFLE GAMES"). The software licensed under this agreement is PICO-8 ("THE SOFTWARE"), including all data files, executables, documentation and design. By distributing, copying, executing, or otherwise using THE SOFTWARE, you agree to be bound by the terms of this license agreement.</p>
                <p>THE SOFTWARE is owned by LEXALOFFLE GAMES. LEXALOFFLE GAMES reserves the exclusive copyright and all rights not expressly granted.</p>
                <p>You may install and use THE SOFTWARE on any computers for which you are the primary user. You may additionally install and use THE SOFTWARE concurrently on any number of computers belonging to a single household or educational organisation, including libraries, clubs, schools and universities.</p>
                <p>Unless express consent is granted by LEXALOFFLE GAMES, you may not distribute all of or any part of THE SOFTWARE to any other party, create derivative works based on THE SOFTWARE, or sell, resell, rent or lease THE SOFTWARE.</p>
            </description>
        </agreement_section>
        <agreement_section id="cartriges">
            <name>EXPORTED CARTRIDGES</name>
            <description>
                <p>Files generated by exporting a cartridge with PICO-8 (Javascript, HTML, executeables and data files) may be used for any purpose, including commercial applications, and to alter them and redistribute them freely, provided that permission to do so is also granted by the authors of the cartridge.</p>
            </description>
        </agreement_section>
        <agreement_section id="disclaimer">
            <name>DISCLAIMER</name>
            <description>
                <p>THE SOFTWARE IS PROVIDED "AS-IS" WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LEXALOFFLE GAMES DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>
                <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LEXALOFFLE GAMES BE LIABLE FOR ANY DAMAGES WHATSOEVER INCLUDING BUT NOT LIMITED TO ANY LOSS OF PRODUCTIVITY, LOSS OF DATA, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF, OR INABILITY TO USE THE SOFTWARE, EVEN IF LEXALOFFLE GAMES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            </description>
        </agreement_section>
    </agreement>
</component>
EOL

wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x ./appimagetool-x86_64.AppImage

./appimagetool-x86_64.AppImage $app_dirname/ "${base_name}-${version}-${ARCH}.AppImage"